# Generated by Django 5.1.2 on 2024-10-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orders_orde_user_id_a87c6f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'product']},
        ),
    ]
