# Generated by Django 5.1.2 on 2024-10-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_products_ca_name_693421_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
